backend:
  name: github
  repo: artemasovvalera/yasam
  branch: main
  Ov23liQvn0C4c21Rbkmb# Вставь сюда свой Client ID:
  # (НЕ публикуй Client Secret в коде!)

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Страницы"
    files:
      - label: "Главная страница"
        name: "index"
        file: "index.html"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Описание", name: "description", widget: "text" }
          - { label: "Содержимое", name: "body", widget: "markdown" }

  - name: "settings"
    label: "Настройки"
    files:
      - label: "Общие"
        name: "general"
        file: "site-config.json"
        fields:
          - { label: "Название", name: "site_name", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
